version: '3'

services:
  app:
    build:
      context: ./src/
    env_file: ./docker.env
    working_dir: /app/src
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
